# Generated by Django 3.2.7 on 2021-09-19 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 13, 46, 26, 596560)),
        ),
    ]
