# Generated by Django 3.2.7 on 2021-09-19 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 13, 47, 21, 199191)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 13, 47, 21, 200178)),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
