# Generated by Django 3.2.7 on 2021-09-19 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_auto_20210919_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 14, 20, 16, 864907)),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 14, 20, 16, 864907)),
        ),
    ]
