# Generated by Django 3.2.7 on 2021-09-20 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210919_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 9, 43, 48, 913028)),
        ),
    ]
